server:
  port: 8090
spring:
  resources:
    static-locations:
    - file:./static/
  freemarker:
    template-loader-path:
    - classpath:/templates/
    - file:./templates/
    cache: false
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: false
  http:
    multipart:
      max-file-size: 2048MB
